---
# zerodowntime.bind9/handlers/main.yml


- name: 'restart bind'
  service:
    name: "{{ bind__service_name }}"
    state: restarted
  become: true

- name: 'reload bind'
  service:
    name: "{{ bind__service_name }}"
    state: reloaded
  become: true
